# Generated by Django 5.2 on 2025-05-07 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'remove_proctoring_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortaassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_assignments', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='TAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergrad_university', models.CharField(blank=True, help_text='University where TA completed undergraduate studies', max_length=100, null=True)),
                ('workload_number', models.PositiveIntegerField(blank=True, help_text='Unique identifier for workload tracking (immutable once set)', null=True, unique=True)),
                ('workload_credits', models.PositiveIntegerField(default=0, help_text='Accumulated workload credits from completed tasks')),
                ('schedule_json', models.JSONField(blank=True, help_text="JSON representation of TA's weekly schedule if not using the WeeklySchedule model", null=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Academic supervisor for this TA', limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tas', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TA Profile',
                'verbose_name_plural': 'TA Profiles',
            },
        ),
    ]
