# Generated by Django 5.2 on 2025-05-09 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('bilkent_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Bilkent ID')),
                ('role', models.CharField(choices=[('TA', 'Teaching Assistant'), ('INSTRUCTOR', 'Course Instructor'), ('STAFF', 'Authorized Staff'), ('DEAN_OFFICE', 'Dean Office'), ('ADMIN', 'Admin')], default='TA', max_length=20)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IE', 'Industrial Engineering'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+905xxxxxxxxx' or '05xxxxxxxxx'.", regex='^\\+?90?\\d{10}$')])),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('academic_level', models.CharField(choices=[('MASTERS', 'Masters'), ('PHD', 'PhD'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', help_text='Employment type affects workload requirement: Full-time requires twice the workload of part-time', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('temp_password', models.CharField(blank=True, max_length=128, null=True)),
                ('temp_password_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ASSIGN', 'Assign'), ('SWAP', 'Swap'), ('OVERRIDE', 'Override'), ('IMPORT', 'Import')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('override_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('PHD', 'PhD')], default='UNDERGRADUATE', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
            options={
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('QUIZ', 'Quiz')], max_length=10)),
                ('date', models.DateTimeField()),
                ('proctor_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WAITING_FOR_STUDENT_LIST', 'Waiting for Student List'), ('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('READY', 'Ready')], default='WAITING_FOR_STUDENT_LIST', max_length=25)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Automatically calculated from the student list file if provided')),
                ('student_list_file', models.FileField(blank=True, help_text='Excel file containing the list of students for this exam', null=True, upload_to='exam_student_lists/')),
                ('has_student_list', models.BooleanField(default=False, help_text='Indicates if a student list has been uploaded')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=3)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.course')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('is_ta', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergrad_university', models.CharField(blank=True, help_text='University where TA completed undergraduate studies', max_length=100, null=True)),
                ('workload_number', models.PositiveIntegerField(blank=True, help_text='Workload category/type for the TA (e.g., 1 or 2, immutable once set)', null=True)),
                ('workload_credits', models.PositiveIntegerField(default=0, help_text='Accumulated workload credits from assigned proctoring duties')),
                ('schedule_json', models.JSONField(blank=True, help_text="JSON representation of TA's weekly schedule if not using the WeeklySchedule model", null=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Academic supervisor for this TA', limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tas', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TA Profile',
                'verbose_name_plural': 'TA Profiles',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(blank=True, help_text='Course name or other details about this class hour', max_length=200)),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorTAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_assignments', to='accounts.department')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tas', to=settings.AUTH_USER_MODEL)),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor-TA Assignment',
                'verbose_name_plural': 'Instructor-TA Assignments',
                'unique_together': {('instructor', 'ta')},
            },
        ),
        migrations.CreateModel(
            name='TAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ta', 'section')},
            },
        ),
    ]
