# Generated by Django 5.2 on 2025-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this TA is currently enrolled in as a student.', related_name='enrolled_tas', to='accounts.course'),
        ),
    ]
