# Generated by Django 5.2 on 2025-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IE', 'Industrial Engineering'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
