# Generated by Django 5.2 on 2025-05-07 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_alter_instructortaassignment_department_taprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proctor_type', models.CharField(choices=[('REGULAR', 'Regular (Unpaid)'), ('PART_TIME', 'Part-Time'), ('PAID', 'Paid')], default='REGULAR', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('credits_awarded', models.PositiveIntegerField(default=0, help_text='Credits awarded for this proctoring assignment')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='accounts.academicterm')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proctorings', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctors', to='accounts.exam')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proctor Assignment',
                'verbose_name_plural': 'Proctor Assignments',
                'unique_together': {('ta', 'exam')},
            },
        ),
    ]
