# Generated by Django 5.2 on 2025-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_temp_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='description',
            field=models.CharField(blank=True, help_text='Course name or other details about this class hour', max_length=200),
        ),
    ]
