# Generated by Django 5.2 on 2025-05-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_academicterm_proctorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctorassignment',
            name='academic_term',
        ),
        migrations.AlterUniqueTogether(
            name='proctorassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proctorassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='proctorassignment',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proctorassignment',
            name='ta',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.DeleteModel(
            name='ProctorAssignment',
        ),
    ]
