# Generated by Django 5.2 on 2025-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_taprofile_enrolled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this TA is currently enrolled in as a student.', related_name='enrolled_tas_profiles', to='accounts.course'),
        ),
    ]
