# Generated by Django 5.2 on 2025-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_taprofile_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration of the exam in minutes'),
        ),
    ]
