# Generated by Django 5.2 on 2025-05-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_proctorassignment_academic_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taprofile',
            name='workload_credits',
            field=models.PositiveIntegerField(default=0, help_text='Accumulated workload credits from assigned proctoring duties'),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='workload_number',
            field=models.PositiveIntegerField(blank=True, help_text='Workload category/type for the TA (e.g., 1 or 2, immutable once set)', null=True),
        ),
    ]
