# Generated by Django 5.2 on 2025-05-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_weeklyschedule_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', help_text='Employment type affects workload requirement: Full-time requires twice the workload of part-time', max_length=20),
        ),
    ]
