# Generated by Django 5.0.6 on 2025-05-11 11:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='helping_department_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_STUDENT_LIST', 'Waiting for Student List'), ('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('WAITING_FOR_CROSS_DEPARTMENT_APPROVAL', 'Waiting for Cross-Department Approval'), ('AWAITING_CROSS_DEPARTMENT_PROCTOR', 'Awaiting Cross-Department Proctor'), ('READY', 'Ready')], default='WAITING_FOR_STUDENT_LIST', max_length=40),
        ),
    ] 