# Generated by Django 5.2 on 2025-05-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_department_student_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorTAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ta_assignments', to='accounts.department')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tas', to=settings.AUTH_USER_MODEL)),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor-TA Assignment',
                'verbose_name_plural': 'Instructor-TA Assignments',
                'unique_together': {('instructor', 'ta')},
            },
        ),
    ]
