# Generated by Django 5.2 on 2025-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_taprofile_workload_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('PHD', 'PhD')], default='UNDERGRADUATE', max_length=20),
        ),
    ]
