# Generated by Django 5.2 on 2025-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='helping_department_code',
            field=models.CharField(blank=True, help_text='Department code of the department helping with proctors, if cross-departmental request is approved.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_STUDENT_LIST', 'Waiting for Student List'), ('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('AWAITING_DEAN_CROSS_APPROVAL', 'Awaiting Dean Approval for Cross-Departmental'), ('AWAITING_CROSS_DEPARTMENT_PROCTORS', 'Awaiting Cross-Department Proctors'), ('READY', 'Ready')], default='WAITING_FOR_STUDENT_LIST', max_length=50),
        ),
    ]
