# Generated by Django 5.2 on 2025-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_exam_helping_department_code_alter_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='helping_department_code',
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_STUDENT_LIST', 'Waiting for Student List'), ('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('WAITING_FOR_CROSS_DEPARTMENT_APPROVAL', 'Waiting for Cross-Department Approval'), ('AWAITING_CROSS_DEPARTMENT_PROCTOR', 'Awaiting Cross-Department Proctor'), ('READY', 'Ready')], default='WAITING_FOR_STUDENT_LIST', max_length=50),
        ),
    ]
