# Generated by Django 5.2 on 2025-05-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructortaassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
