# Generated by Django 5.2 on 2025-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classroom',
        ),
        migrations.AddField(
            model_name='exam',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='exams', to='accounts.classroom'),
        ),
    ]
