# Generated by Django 5.2 on 2025-05-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_exam_classroom_exam_classrooms'),
    ]

    operations = [
    ]
