# Generated by Django 5.2 on 2025-05-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('READY', 'Ready')], default='WAITING_FOR_PLACES', max_length=20),
        ),
    ]
