# Generated by Django 5.2 on 2025-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_exam_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='has_student_list',
            field=models.BooleanField(default=False, help_text='Indicates if a student list has been uploaded'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Automatically calculated from the student list file if provided'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_list_file',
            field=models.FileField(blank=True, help_text='Excel file containing the list of students for this exam', null=True, upload_to='exam_student_lists/'),
        ),
    ]
