# Generated by Django 5.2 on 2025-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_exam_has_student_list_exam_student_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_STUDENT_LIST', 'Waiting for Student List'), ('WAITING_FOR_PLACES', 'Waiting for Places'), ('AWAITING_PROCTORS', 'Awaiting Proctors'), ('READY', 'Ready')], default='WAITING_FOR_STUDENT_LIST', max_length=25),
        ),
    ]
