# Generated by Django 5.2 on 2025-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_revert_classroom_to_foreignkey'),
        ('accounts', '0012_revert_classroom_to_foreignkey'),
    ]

    operations = [
    ]
