# Generated by Django 5.2 on 2025-05-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_section_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bilkent_id',
            field=models.CharField(blank=True, help_text='Unique 8-digit Bilkent University ID number', max_length=8, null=True, verbose_name='Bilkent ID'),
        ),
    ]
