# Generated by Django 5.2 on 2025-05-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_bilkent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bilkent_id',
        ),
        migrations.AddField(
            model_name='taprofile',
            name='bilkent_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
