# Generated by Django 5.2 on 2025-05-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TADuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('minutes', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_duties', to=settings.AUTH_USER_MODEL)),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='duties.dutytype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_duties', to='accounts.section')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TA Duty',
                'verbose_name_plural': 'TA Duties',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_type', models.CharField(choices=[('PROCTOR', 'Proctoring Hours'), ('DUTY', 'TA Duty Hours'), ('TOTAL', 'Total Workload')], max_length=10)),
                ('academic_level', models.CharField(blank=True, choices=[('MASTERS', 'Masters'), ('PHD', 'PhD'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20, null=True)),
                ('department_code', models.CharField(blank=True, max_length=10, null=True)),
                ('period', models.CharField(choices=[('SEMESTER', 'Per Semester'), ('YEAR', 'Per Academic Year')], default='SEMESTER', max_length=10)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cap_type', 'academic_level', 'department_code', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('proctor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('task_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='workload_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workload Summary',
                'verbose_name_plural': 'Workload Summaries',
                'unique_together': {('ta', 'semester', 'year')},
            },
        ),
    ]
