# Generated by Django 5.2 on 2025-05-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_taclassschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TAClassSchedule',
        ),
    ]
