# Generated by Django 5.2 on 2025-05-08 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_section_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('bilkentID', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
