# Generated by Django 5.2 on 2025-05-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='bilkentID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
