# Generated by Django 5.2 on 2025-05-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadpolicy',
            name='max_hours_msc',
        ),
        migrations.RemoveField(
            model_name='workloadpolicy',
            name='max_hours_phd',
        ),
        migrations.AddField(
            model_name='taworkload',
            name='required_workload_hours',
            field=models.FloatField(default=0.0, help_text='Total hours required to complete based on employment type'),
        ),
        migrations.AddField(
            model_name='workloadpolicy',
            name='max_hours_msc_full_time',
            field=models.PositiveIntegerField(default=15, help_text='Maximum weekly hours for Full-Time MSc TAs'),
        ),
        migrations.AddField(
            model_name='workloadpolicy',
            name='max_hours_msc_part_time',
            field=models.PositiveIntegerField(default=7, help_text='Maximum weekly hours for Part-Time MSc TAs'),
        ),
        migrations.AddField(
            model_name='workloadpolicy',
            name='max_hours_phd_full_time',
            field=models.PositiveIntegerField(default=20, help_text='Maximum weekly hours for Full-Time PhD TAs'),
        ),
        migrations.AddField(
            model_name='workloadpolicy',
            name='max_hours_phd_part_time',
            field=models.PositiveIntegerField(default=10, help_text='Maximum weekly hours for Part-Time PhD TAs'),
        ),
    ]
