# Generated by Django 5.2 on 2025-05-04 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_department_student_department_name_and_more'),
        ('tasks', '0002_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('can_assign_tasks', 'Can assign tasks to TAs'), ('can_manage_own_tasks', 'Can manage own tasks')]},
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.AddField(
            model_name='task',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='When the instructor approved this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='When the TA marked this task as completed', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='task',
            name='instructor_feedback',
            field=models.TextField(blank=True, help_text='Feedback from instructor, required for rejections'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('LAB', 'Laboratory Session'), ('GRADING', 'Grading Assignment'), ('RECITATION', 'Recitation Session'), ('OFFICE_HOUR', 'Office Hour'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='credit_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Credit hours that will be added to TA's workload when approved", max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed by TA'), ('APPROVED', 'Approved by Instructor'), ('REJECTED', 'Rejected by Instructor')], default='ASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
