# Generated by Django 5.2 on 2025-05-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_exam_helping_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assisting_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments approved to assist with proctoring for this exam.', related_name='assisting_exams', to='accounts.department'),
        ),
    ]
