# Generated by Django 5.2 on 2025-05-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_exam_assisting_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ASSIGN', 'Assign'), ('SWAP', 'Swap'), ('OVERRIDE', 'Override'), ('IMPORT', 'Import'), ('NOTIFY_TAS', 'Notify TAs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification.')),
                ('notification_type', models.CharField(choices=[('PROCTORING_INVITATION', 'Proctoring Invitation'), ('PROCTORING_ASSIGNMENT', 'Proctoring Assignment'), ('EXAM_UPDATE', 'Exam Update'), ('GENERAL_INFO', 'General Information'), ('TASK_ASSIGNMENT', 'Task Assignment'), ('LEAVE_REQUEST_STATUS', 'Leave Request Status')], default='GENERAL_INFO', help_text='The type of notification.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Has the user read this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read.', null=True)),
                ('link', models.CharField(blank=True, help_text='A URL link related to the notification, e.g., to view the exam details.', max_length=255, null=True)),
                ('related_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.exam')),
                ('user', models.ForeignKey(help_text='The user who will receive the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
