# Generated by Django 4.2 on 2025-05-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='max_days_per_semester',
        ),
    ]
