# Generated by Django 5.2 on 2025-05-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('QUIZ', 'Quiz'), ('MAKEUP', 'Makeup'), ('OTHER', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('student_count', models.PositiveIntegerField()),
                ('proctor_count_needed', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField(default=1)),
                ('student_list_file', models.FileField(blank=True, null=True, upload_to='exam_student_lists/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_cross_department', models.BooleanField(default=False)),
                ('dean_office_request', models.BooleanField(default=False)),
                ('dean_office_comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('requested_from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_proctorings', to='accounts.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.section')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField()),
                ('proctor_count', models.PositiveIntegerField(default=1)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='proctoring.exam')),
            ],
            options={
                'unique_together': {('exam', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('SWAPPED', 'Swapped'), ('DECLINED', 'Declined')], default='ASSIGNED', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('override_flag', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proctorings', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='proctoring.exam')),
                ('exam_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='proctoring.examroom')),
                ('proctor', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'proctor')},
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FORCE_SWAP', 'Force Swap')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force_swap', models.BooleanField(default=False)),
                ('force_swap_reason', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('force_swap_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_swaps', to=settings.AUTH_USER_MODEL)),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_original', to='proctoring.proctorassignment')),
                ('requested_proctor', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_target', to=settings.AUTH_USER_MODEL)),
                ('requesting_proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctorConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_date', models.DateField(blank=True, null=True)),
                ('constraint_type', models.CharField(choices=[('PHD_REQUIRED', 'PhD Required for Grad Courses'), ('OWN_EXAM', 'Student in Course'), ('SCHEDULE_CONFLICT', 'Schedule Conflict'), ('LEAVE_DAY', 'Approved Leave'), ('OTHER', 'Other Constraint')], max_length=20)),
                ('description', models.TextField()),
                ('can_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_constraints', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_constraints', to='proctoring.exam')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_constraints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ta', 'exam', 'constraint_type')},
            },
        ),
    ]
