# Generated by Django 5.2 on 2025-05-07 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_proctorassignment_academic_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='ASSIGNED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'ADMIN', 'INSTRUCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='accounts.exam')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proctor Assignment',
                'verbose_name_plural': 'Proctor Assignments',
                'unique_together': {('exam', 'ta')},
            },
        ),
    ]
