# Generated by Django 5.2 on 2025-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorassignment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Is this a paid proctoring assignment?'),
        ),
    ]
