# Generated by Django 5.2 on 2025-05-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorassignment',
            name='previous_proctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_proctor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctorassignment',
            name='swap_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctorassignment',
            name='swap_depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this assignment has been swapped'),
        ),
        migrations.AddField(
            model_name='proctorassignment',
            name='swap_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proctorassignment',
            name='swap_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='constraint_check_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='constraint_check_passed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='is_auto_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='is_cross_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FORCE_SWAP', 'Force Swap'), ('AUTO_SWAP', 'Automatic Swap')], default='PENDING', max_length=10),
        ),
    ]
