# Generated by Django 5.2 on 2025-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('grading', 'Assignment Grading'), ('lab_assistance', 'Lab Assistance'), ('tutorial', 'Tutorial Session'), ('office_hours', 'Office Hours'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
