# Generated by Django 4.2 on 2025-05-11 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctoring', '0002_proctorassignment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorassignment',
            name='swap_depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this assignment has been swapped'),
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason provided by requester for the swap')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched with another TA'), ('APPROVED', 'Approved by instructor'), ('REJECTED', 'Rejected by instructor'), ('CANCELLED', 'Cancelled by requester'), ('COMPLETED', 'Swap completed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_comment', models.TextField(blank=True, help_text='Comment from instructor when approving/rejecting the swap')),
                ('rejected_reason', models.TextField(blank=True, help_text='Reason for rejection by the instructor or system')),
                ('matched_assignment', models.ForeignKey(blank=True, help_text='The proctoring assignment offered by the matched proctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_swap_requests', to='proctoring.proctorassignment')),
                ('matched_proctor', models.ForeignKey(blank=True, help_text='TA who accepted to swap with the requester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_swaps', to=settings.AUTH_USER_MODEL)),
                ('original_assignment', models.ForeignKey(help_text='The proctoring assignment that the requesting TA wants to swap', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='proctoring.proctorassignment')),
                ('requesting_proctor', models.ForeignKey(help_text='TA who initiated the swap request', on_delete=django.db.models.deletion.CASCADE, related_name='requested_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swap Request',
                'verbose_name_plural': 'Swap Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
