# Generated by Django 5.2 on 2025-05-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctorassignment_previous_proctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason for the swap request'),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requested_proctor',
            field=models.ForeignKey(blank=True, help_text='Target TA for the swap. Leave blank for general availability posting.', limit_choices_to={'role': 'TA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FORCE_SWAP', 'Force Swap'), ('AUTO_SWAP', 'Automatic Swap'), ('AVAILABLE', 'Available for Swap')], default='PENDING', max_length=10),
        ),
    ]
