# Generated by Django 5.2 on 2025-05-05 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructortaassignment'),
        ('proctoring', '0003_alter_swaprequest_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDeptProctorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_count', models.PositiveIntegerField(default=1)),
                ('filled_count', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly payment rate for cross-department proctoring', max_digits=6)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['DEAN_OFFICE', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_cross_dept_calls', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dept_calls', to='accounts.department')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dept_calls', to='proctoring.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CrossDeptProctorClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['DEAN_OFFICE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cross_dept_claims', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_dept_claim', to='proctoring.proctorassignment')),
                ('proctor_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='proctoring.crossdeptproctorcall')),
                ('ta', models.ForeignKey(limit_choices_to={'role': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='cross_dept_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proctor_call', 'ta')},
            },
        ),
    ]
