# Generated by Django 5.2 on 2025-05-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_crossdeptproctorcall_crossdeptproctorclaim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossDeptProctorClaim',
        ),
        migrations.DeleteModel(
            name='CrossDeptProctorCall',
        ),
    ]
